name: Deploy to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch: # Déploiement manuel aussi disponible

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.ACTION_ECORIDE }}
        port: 22
        script: |
          echo "Starting deployment..."
          cd ${{ secrets.PROJECT_PATH_ON_SERVER }}
          
          # Pull latest changes
          git pull origin master
          
          # Install dependencies if composer.json changed
          if git diff --name-only HEAD~1 HEAD | grep -q "composer"; then
            echo "Installing Composer dependencies..."
            composer install --no-dev --optimize-autoloader --no-interaction
          fi
          
          # Build assets if needed
          if git diff --name-only HEAD~1 HEAD | grep -q -E "(package\.json|webpack|assets/)"; then
            echo "Building frontend assets..."
            npm install
            npm run build
          fi
          
          # Run migrations if needed
          if git diff --name-only HEAD~1 HEAD | grep -q "migrations/"; then
            echo "Running database migrations..."
            php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
          fi
          
          # Clear cache
          echo "Clearing cache..."
          php bin/console cache:clear --env=prod
          
          echo "Deployment completed successfully!"
